server:
  port: 80

spring:
  application:
    name: cloud-order-service
  #服务链路-链路跟踪-数据采集整理
  sleuth:
    sampler:
      #采样率值 介于0到1直接，为1全部采集
      probability: 1
  #服务链路-链路跟踪-数据展示
  zipkin:
    #采样后的数据发布的地址
    base-url: http://localhost:9411

eureka:
  #客户端的配置主要是：是否向注册中心注册自己、是否想注册中心获取注册信息；注册中心地址
  client:
    #向服务注册中心注册自己
    register-with-eureka: true
    #从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    #给Eureka客户端使用的地址，服务端地址7001，不用输入后面的eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


