server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    #统一访问网关进行转发
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #注意:不是HTTP开头
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
          filters:
            - AddRequestParameter=red,blue
        - id: payment_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - Method=Get
#            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性；并且属性值为整数（正则匹配）
#            - Cookie=username,zzyy
#            - After=2020-05-06T17:52:11.834+08:00[Asia/Shanghai]
#            - Before=2020-04-06T17:52:11.834+08:00[Asia/Shanghai]
#            - Between=2020-04-06T17:52:11.834+08:00[Asia/Shanghai],2020-04-06T17:52:11.834+08:00[Asia/Shanghai]


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #向服务注册中心注册自己
    register-with-eureka: true
    #从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    #给Eureka客户端使用的地址，服务端地址7001，不用输入后面的eureka
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/


